trigger:
  branches:
    include:
      - dev
      - master
      - preview/*
      - releases/*

pr:
  autoCancel: false
  branches:
    include:
      - dev
      - master
      - preview/*
      - releases/*

jobs:
- job: build
  pool:
    name: 'Hosted VS2017'  # name of the pool to run this job in
    demands:
      - msbuild
      - visualstudio
      - vstest
  steps:
    - checkout: self
      clean: false
      submodules: true

    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: restore

    - task: PowerShell@2
      displayName: 'PowerShell Script build.ps1'
      inputs:
        targetType: filePath
        filePath: ./build.ps1
        arguments: '-devSetup -install AppAndDependencies -test -verbose'
